import { getTransformedPermissions } from './utils';

export const permissionTypes = [
  { key: 'create', prefix: 'write' },
  { key: 'update', prefix: 'patch' },
  { key: 'view', prefix: 'read' },
  { key: 'delete', prefix: 'delete' },
  { key: 'download', prefix: 'download' },
];

export const permissionsData = [
  {
    id: 1,
    modules: 'Home',
    subModules: 'Dashboard-Widgets',
    functionality: '',
    create: false, // For checkbox visibility in Table (true: visible, false: hidden)
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'dashboard', // Module permission name
    moduleName: 'dashboard', // For sidebar menu permissions logic
  },
  {
    id: 2,
    modules: 'Fleet Management',
    subModules: 'Fleet View',
    functionality: 'Map',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'fleet-map-view',
    moduleName: 'fleet-view',
  },
  {
    id: 3,
    modules: '',
    subModules: 'Fleet View',
    functionality: 'List',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'fleet-list-view',
    moduleName: 'fleet-view',
  },
  {
    id: 36,
    modules: '',
    subModules: 'Fleet View',
    functionality: 'Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'fleet-list-view-details',
    moduleName: 'fleet-view',
  },
  // {
  //   id: 4,
  //   modules: '',
  //   subModules: 'Equipment Listing',
  //   functionality: 'List',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 5,
  //   modules: '',
  //   subModules: 'Equipment Listing',
  //   functionality: 'Details',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: false,
  // },
  {
    id: 6,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Activity Feed',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: true,
    modulePermission: 'telematics-activity-feed',
    moduleName: 'telematics',
  },
  {
    id: 39,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Activity Feed - Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'telematics-activity-feed-details',
    moduleName: 'telematics',
  },
  {
    id: 33,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Geofence',
    create: true,
    update: true,
    view: false,
    delete: true,
    download: false,
    modulePermission: 'geofence',
    moduleName: 'telematics',
  },

  {
    id: 8,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Geofence - Map View',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'geofence-map-view',
    moduleName: 'telematics',
  },
  {
    id: 7,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Geofence - List View',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'geofence-list-view',
    moduleName: 'telematics',
  },
  {
    id: 34,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Geofence - Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'geofence-list-view-details',
    moduleName: 'telematics',
  },
  {
    id: 9,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Telematics Alerts - List',
    create: true,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'telematics-alerts',
    moduleName: 'telematics',
  },
  {
    id: 40,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Telematics Alerts - Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'telematics-alerts-details',
    moduleName: 'telematics',
  },
  {
    id: 10,
    modules: '',
    subModules: 'DOT Inspection',
    functionality: 'List',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: true,
    modulePermission: 'dot-inspection',
    moduleName: 'dot-pm-compliance',
  },
  {
    id: 11,
    modules: '',
    subModules: 'DOT Inspection',
    functionality: 'Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'dot-inspection-details',
    moduleName: 'dot-pm-compliance',
  },
  {
    id: 37,
    modules: '',
    subModules: 'Preventive Maintenance',
    functionality: 'List',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: true,
    modulePermission: 'preventive-maintanence',
    moduleName: 'dot-pm-compliance',
  },
  {
    id: 38,
    modules: '',
    subModules: 'Preventive Maintenance',
    functionality: 'Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'preventive-maintanence-details',
    moduleName: 'dot-pm-compliance',
  },
  {
    id: 12,
    modules: '',
    subModules: 'Agreements',
    functionality: 'Lease - List',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: true,
    modulePermission: 'lease',
    moduleName: 'agreements',
  },
  {
    id: 13,
    modules: '',
    subModules: 'Agreements',
    functionality: 'Lease - Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'lease-details',
    moduleName: 'agreements',
  },
  {
    id: 14,
    modules: '',
    subModules: 'Agreements',
    functionality: 'Rental - List',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: true,
    modulePermission: 'rental',
    moduleName: 'agreements',
  },
  {
    id: 15,
    modules: '',
    subModules: 'Agreements',
    functionality: 'Rental - Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'rental-details',
    moduleName: 'agreements',
  },
  // {
  //   id: 16,
  //   modules: 'TEN Care',
  //   subModules: 'Work Orders (M&R)',
  //   functionality: 'List',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 17,
  //   modules: 'TEN Care',
  //   subModules: 'Work Orders (M&R)',
  //   functionality: 'Details',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: false,
  // },

  // {
  //   id: 18,
  //   modules: '',
  //   subModules: 'TEN Care ERS',
  //   functionality: 'List',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 19,
  //   modules: '',
  //   subModules: 'TEN Care ERS',
  //   functionality: 'Details',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: false,
  // },
  // {
  //   id: 20,
  //   modules: '',
  //   subModules: 'Request Service History',
  //   functionality: 'List',
  //   create: true,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 21,
  //   modules: '',
  //   subModules: 'Request Service History',
  //   functionality: 'Details',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 22,
  //   modules: 'Billing',
  //   subModules: 'Invoices',
  //   functionality: 'List',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 23,
  //   modules: '',
  //   subModules: 'Invoices',
  //   functionality: 'Pay Now',
  //   create: true,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: false,
  // },
  // {
  //   id: 24,
  //   modules: '',
  //   subModules: 'Invoices',
  //   functionality: 'Details',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 25,
  //   modules: '',
  //   subModules: 'Payments',
  //   functionality: 'List',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 26,
  //   modules: '',
  //   subModules: 'Payments',
  //   functionality: 'Details',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 27,
  //   modules: 'Reports',
  //   subModules: 'Report Explorer',
  //   functionality: 'List',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  // {
  //   id: 28,
  //   modules: '',
  //   subModules: 'Report Explorer',
  //   functionality: 'Details',
  //   create: false,
  //   update: false,
  //   view: true,
  //   delete: false,
  //   download: true,
  // },
  {
    id: 29,
    modules: 'Account Management',
    subModules: 'Accounts',
    functionality: 'List',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: true,
    modulePermission: 'accounts',
    moduleName: 'accounts',
  },
  {
    id: 30,
    modules: '',
    subModules: 'Accounts',
    functionality: 'Details',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'account-details',
    moduleName: 'accounts',
  },
  {
    id: 31,
    modules: '',
    subModules: 'User Management',
    functionality: 'TEN Users - List',
    create: false,
    update: false,
    view: true,
    delete: false,
    download: false,
    modulePermission: 'user-management-ten-user-list',
    moduleName: 'user-management',
  },
  {
    id: 32,
    modules: '',
    subModules: 'User Management',
    functionality: 'Customer Users - List',
    create: false,
    update: true,
    view: true,
    delete: false,
    download: true,
    modulePermission: 'user-management',
    moduleName: 'user-management',
  },
  {
    id: 35,
    modules: '',
    subModules: 'User Management',
    functionality: 'Assign Role',
    create: false,
    update: true,
    view: false,
    delete: false,
    download: false,
    modulePermission: 'user-management-assign-role',
    moduleName: 'user-management',
  },
  {
    id: 41,
    modules: '',
    subModules: 'User Roles and Permissions',
    functionality: 'Role',
    create: true,
    update: true,
    view: false,
    delete: true,
    download: false,
    modulePermission: 'role',
    moduleName: 'user-management',
  },
];

export const allPermissions = getTransformedPermissions(permissionsData);
