export const LeaseOverviewData = [
  {
    title: 'Agreement Overview',
    items: [
      { label: 'Master Agreement', value: 'June 2, 2025' },
      { label: 'Schedule A', value: 'July 30, 2025' },
      { label: 'Schedule A Group', value: 'June 1, 2025 to July 31, 2025' },
    ],
  },
  {
    title: 'Location & Facility Info',
    items: [
      { label: 'TEN Facility', value: 'John Doe' },
      { label: 'Domicile Location', value: 'johndoe@gmail.com' },
      { label: 'Customer Pool / Group', value: 'Jun 5, 2025' },
    ],
  },
  {
    title: 'Contractual / Lease Info',
    items: [
      { label: 'Account #', value: 'ACC-123456' },
      { label: 'Lease PO #', value: '#1DWIA53222S534114' },
      { label: 'Lease Start Date', value: 'Jan 1, 2025' },
      { label: 'Early Termination Option Date', value: 'Oct 15, 2025' },
      { label: 'Full Lease Termination Date', value: 'Dec 31, 2026' },
      { label: 'Unit Picked Up Date', value: 'Nov 20, 2025' },
      { label: 'Unit Turned In Date', value: 'Feb 2, 2027' },
    ],
  },
  {
    title: 'Unit Identifiers',
    items: [
      { label: 'Unit #', value: 'U-45678' },
      { label: 'Customer Unit #', value: 'CUST-9988' },
      { label: 'License Plate', value: 'KA-01-AB-1234' },
      { label: 'Year / Make / Model / Length', value: '2022 / Strick / Dry Van / 53ft' },
      { label: 'VIN', value: '1DW1A5322NS534114' },
      { label: 'Type', value: 'Swing Door' },
      { label: 'Description', value: 'Dry Van trailer used for interstate shipping' },
    ],
  },
  {
    title: 'Billing Info',
    items: [
      { label: 'Billing Interval', value: 'Monthly' },
      { label: 'Fixed Rate', value: '$1200' },
      { label: 'Variable Rate', value: '$0.15 per mile' },
    ],
  },
  {
    title: 'Gate Inspection Info',
    items: [
      { label: 'TEN Master MTSLA', value: '202112101', isLink: true },
      { label: 'TEN Master NMS', value: '202112102', isLink: true },
      { label: 'Schedule A', value: '202112103', isLink: true },
      { label: 'Schedule S', value: '202112104', isLink: true },
      { label: 'Star SC', value: '202112105', isLink: true },
    ],
  },
];

export const rentAgreementOverview = [
  {
    title: 'Unit Identifiers',
    items: [
      { label: 'Unit #', value: 'June 2, 2025' },
      { label: 'Customer Unit #', value: 'July 30, 2025' },
      { label: 'Plate #', value: 'TH-02-1849' },
      { label: 'State', value: 'Illinois' },
      { label: 'VIN', value: '#4698/33' },
    ],
  },

  {
    title: 'Facility & Location',
    items: [
      { label: 'TEN Facility', value: 'John Doe' },
      { label: 'Domicile Location', value: 'johndoe@gmail.com' },
      { label: 'Customer Pool / Group', value: 'Jan 5, 2025' },
      { label: 'Reservation', value: 'Jun 5, 2025' },
    ],
  },
  {
    title: 'Unit Description',
    items: [
      { label: 'Year / Maker / Model', value: '2021 / Great Done / Everest SS Reefer' },
      { label: 'Length', value: '55 ft' },
      { label: 'Type', value: 'Reefer' },
    ],
  },
  {
    title: 'Lease Status',
    items: [
      { label: 'Start Date', value: 'June 2, 2025' },
      { label: 'End Date', value: '#IDWIA532225934H4' },
      { label: 'Status', value: 'STRICK CORPORATION' },
    ],
  },
  {
    title: 'Billing Info',
    items: [
      { label: 'Billing Interval', value: 'Daily' },
      { label: 'Account #', value: '#SYN-62400134' },
      { label: 'Fixed Rate', value: '¥35,000/month for 12 months' },
      { label: 'Variable Rate', value: '¥30,000/month base rate - ¥24mn after 2,000 km' },
      { label: 'PO #', value: '#IEi8347685XS' },
    ],
  },

  {
    title: 'Gate Inspection Info',
    items: [
      { label: 'Location', value: 'June 2, 2025' },
      { label: 'Direction', value: '#IDWIA532225934H4' },
      { label: 'Date', value: 'STRICK CORPORATION' },
      { label: 'File Download', value: 'Jan 1, 2025 - Dec 31, 2025' },
    ],
  },
];

export const invoiceOverviewData = [
  {
    title: 'Invoice Billing',
    items: [
      { label: 'Date', value: 'June 2, 2025' },
      { label: 'Due Date', value: 'July 30, 2025' },
      { label: 'Billing Period', value: 'June 1, 2025 to July 31, 2025' },
    ],
  },
  {
    title: 'Customer & Billing Info',
    items: [
      { label: 'Billing Address', value: '636 Greenwich St. New York.' },
      { label: 'Contact Info', value: 'alexrmax@gmail.com' },
      { label: 'Tax ID', value: 'TAXD-458458E-56785' },
    ],
  },
  {
    title: 'Equipment Covered',
    items: [
      { label: 'List of Unit build', value: '432 Units' },
      { label: 'Aliases', value: 'Max Alex' },
      { label: 'Locations', value: 'TAXD-458458E-56785' },
    ],
  },
];

export const invoicePaymentOverviewData = [
  {
    title: 'Payment Summary',
    items: [
      { label: 'Sub total', value: '$360.00' },
      { label: 'Taxes', value: '$12.00' },
      { label: 'Discounts', value: '$10.00' },
      { label: 'Credits', value: '$12.00' },
      { label: 'Total Amount Paid', value: '$320.00' },
      { label: 'Amount Paid', value: '$280.00' },
      { label: 'Balance Due', value: '$40.00' },
    ],
  },
];

export const paymentOverviewData = [
  {
    title: 'Payment Details',
    items: [
      { label: 'Payment ID', value: 'TXNID245533632' },
      { label: 'Payment Date', value: 'July 11, 2025' },
      { label: 'Payment Method', value: 'Credit Card' },
      { label: 'Payer Name / Entity', value: 'Max Alex' },
    ],
  },
  {
    title: 'Invoice Payments',
    items: [
      {
        label: '211349586',
        value: 'HERITAGE-CRYSTAL CLEAN, LLC (001-10024255-224) — $432.05',
      },
      {
        label: '211349566',
        value: 'HERITAGE-CRYSTAL CLEAN, LLC (001-10024255-224) — $262.05',
      },
      {
        label: '211349572',
        value: 'HERITAGE-CRYSTAL CLEAN, LLC (001-10024255-224) — $132.05',
      },
    ],
  },
  {
    title: 'Payment Summary',
    items: [
      { label: 'Invoice Payments (3)', value: '$948.18' },
      { label: 'Invoice Credits(0)', value: '$0.00' },
      { label: 'Payment amount', value: '$948.18' },
    ],
  },
];

export const accountViewPrimaryData = [
  {
    title: '',
    items: [
      { label: 'Name', value: 'Jasper Leo' },
      { label: 'Account #', value: '#00054-895024' },
      { label: 'Customer Ref#', value: '#SYN-62400082' },
      { label: 'Location', value: 'North Decatur, GA, USA' },
    ],
  },
];

/* emergency response details data */
export const emergencyResponseOverviewData = [
  {
    title: 'ERS Details',
    items: [
      { label: 'ERS Case ID', value: 'ERS-10925' },
      { label: 'Status', value: 'Open' },
      { label: 'Created Time', value: 'June 1,2025 to July 31,2025' },
      { label: 'Equipment Id', value: 'Trailer TX-3471' },
      { label: 'Event Type', value: 'Flat Tire' },
    ],
  },
  {
    title: 'Vendor Assignment & ETA',
    items: [
      {
        label: 'Vendor Name',
        value: 'SpeedFix Auto Service',
      },
      {
        label: 'Assigned Technician',
        value: 'John Doe',
      },
      {
        label: 'ETA',
        value: 'June 1,2025 to July 31,2025',
      },
      {
        label: 'Contact Info',
        value: 'Email',
      },
      {
        label: 'Work Order Id',
        value: '229494',
        isLink: true,
      },
    ],
  },
  {
    title: 'Incident Summary',
    items: [
      { label: 'Reported By', value: 'John Doe' },
      { label: 'Time of Incidence', value: 'June 2,2025-10:12AM' },
      { label: 'Location Description', value: 'June 2,2025' },
      { label: 'Urgency Level', value: 'High' },
    ],
  },
  {
    title: 'Driver Notes',
    items: [{ label: 'Notes', value: 'John Doe' }],
  },
];

export const WorkOrderDetailsData = [
  {
    title: 'Work Order Details',
    items: [
      { label: 'Work Order ID', value: 'June 2, 2025' },
      { label: 'Status', value: 'July 30, 2025' },
      { label: 'Created On', value: 'June 1, 2025 to July 31, 2025' },
      { label: 'Last Updated', value: 'June 04, 2025 - 10:00 AM' },
    ],
  },
  {
    title: 'Vendor/Technician Assigned',
    items: [
      { label: 'Contact Info', value: 'johndoe@gmail.com' },
      { label: 'Assignment Date', value: 'Jun 5, 2025' },
      { label: 'Request Service ID', value: 'TNX56335522' },
      { label: 'Reported By', value: 'John Doe' },
      { label: 'Reported On', value: 'July 18, 2025' },
    ],
  },
  {
    title: 'Equipment Details',
    items: [
      { label: 'Asset ID / Name', value: 'June 2, 2025' },
      { label: 'Warranty Info (if any)', value: 'None Specified' },
      { label: 'Make / Model', value: 'Jan 1, 2025 – Dec 31, 2025' },
      { label: 'Repair Type', value: 'Schedule PM' },
      { label: 'Location', value: 'STRICK CORPORATION' },
      { label: 'Estimate Time Arrival', value: 'June 02, 2025' },
      { label: 'Serial Number', value: '#1DW1A532225S34114' },
      { label: 'Actual Time Arrival', value: 'June 02, 2025' },
      { label: 'Operating Hours / Mileage', value: 'Swing Door' },
      { label: 'Uploaded Documents', value: 'Document.pdf' },
    ],
  },
];

export const userManagementRows = [
  {
    id: 1,
    name: 'Stella Elsa',
    email: 'stellaelsa@gmail.com',
    title: 'Marketing Specialist',
    pa_name: { value: 'Synergy Innovations' },
    first_active: 'June 15, 2025',
    last_active: 'June 15, 2025',
    status: { value: 'active' },
    designation: 'Marketing Specialist',
    role: 'Customer Admin',
    account: { value: 'Mindwave LLC', id: '#ID 543923' },
  },
  {
    id: 2,
    name: 'Oliver Miller',
    email: 'olivermiller@gmail.com',
    title: 'Marketing Specialist',
    pa_name: { value: 'Pinnacle Analytics' },
    first_active: 'June 15, 2025',
    last_active: 'June 15, 2025',
    status: { value: 'active' },
    designation: 'Marketing Specialist',
    role: 'Customer Admin',
    account: { value: 'Mindwave LLC', id: '#ID 543923' },
  },
  {
    id: 3,
    name: 'Noah Brown',
    email: 'noahbr@gmail.com',
    title: 'Backend Developer',
    pa_name: { value: 'Catalyst Media' },
    first_active: 'June 9, 2025',
    last_active: 'June 9, 2025',
    status: { value: 'suspended' },
    designation: 'Backend Developer',
    role: 'Basic User',
    account: { value: 'Mindwave LLC', id: '#ID 543923' },
  },
  {
    id: 4,
    name: 'Rodriguez',
    email: 'Rodir@gmail.com',
    title: 'Graphic Designer',
    pa_name: { value: 'Horizon Enterprises' },
    first_active: 'June 13, 2025',
    last_active: 'June 13, 2025',
    status: { value: 'suspended' },
    designation: 'Graphic Designer',
    role: 'Expert User',
    account: { value: 'Google LLC', id: '#ID 543923' },
  },
  {
    id: 6,
    name: 'Liam Johnson',
    email: 'liamjohnson@example.com',
    title: 'UX Designer',
    pa_name: { value: 'Impact Digital' },
    first_active: 'June 7, 2025',
    last_active: 'June 7, 2025',
    status: { value: 'active' },
    designation: 'UX Designer',
    role: 'Customer Admin',
    account: { value: 'Google LLC', id: '#ID 543923' },
  },
  {
    id: 7,
    name: 'Alexander Lee',
    email: 'alexanderlee@example.com',
    title: 'Web Developer',
    pa_name: { value: 'Infinity Group' },
    first_active: 'June 17, 2025',
    last_active: 'June 17, 2025',
    status: { value: 'suspended' },
    designation: 'Web Developer',
    role: 'Customer Admin',
    account: { value: 'Mindwave LLC', id: '#ID 543923' },
  },
  {
    id: 8,
    name: 'Ava Martinez',
    email: 'avamartinez@example.com',
    title: 'Data Analyst',
    pa_name: { value: 'Nexus Dynamics' },
    first_active: 'June 10, 2025',
    last_active: 'June 10, 2025',
    status: { value: 'active' },
    designation: 'Data Analyst',
    role: 'Customer Admin',
    account: { value: 'Mindwave LLC', id: '#ID 543923' },
  },
  {
    id: 9,
    name: 'Luna Rita',
    email: 'lunaherna@example.com',
    title: 'Social Media Manager',
    pa_name: { value: 'Quantum Tech' },
    first_active: 'June 14, 2025',
    last_active: 'June 14, 2025',
    status: { value: 'active' },
    designation: 'Social Media Manager',
    role: 'Customer Admin',
    account: { value: 'Mindwave LLC', id: '#ID 543923' },
  },
  {
    id: 10,
    name: 'Isabella Davis',
    email: 'lunahernandez@example.com',
    title: 'Content Writer',
    pa_name: { value: 'Echo Services' },
    first_active: 'June 12, 2025',
    last_active: 'June 12, 2025',
    status: { value: 'active' },
    designation: 'Content Writer',
    role: 'Customer Admin',
    account: { value: 'Mindwave LLC', id: '#ID 543923' },
  },
  {
    id: 11,
    name: 'Mia Garcia',
    email: 'olivermiller@example.com',
    title: 'Frontend Developer',
    pa_name: { value: 'Infinity Group' },
    first_active: 'June 8, 2025',
    last_active: 'June 8, 2025',
    status: { value: 'suspended' },
    designation: 'Frontend Developer',
    role: 'Customer Admin',
    account: { value: 'Mindwave LLC', id: '#ID 543923' },
  },
];

export const requestServiceHistoryRows = [
  {
    trailer: '1945252B',
    submitted_on: 'July 11, 2025, 9:45 AM',
    submitted_by: 'Mackenzie Mabrey',
    issue: 'Body Components',
    repaired_by: 'July 12, 2025, 15:45 PM',
    location: 'TEN Care',
  },
  {
    trailer: '1945253D',
    submitted_on: 'July 12, 2025, 9:52 AM',
    submitted_by: 'Jacqueline Boyle',
    issue: 'Brakes',
    repaired_by: 'July 14, 2025, 14:24 PM',
    location: 'TEN Care',
  },
  {
    trailer: '1945252B',
    submitted_on: 'July 14, 2025, 10:30 AM',
    submitted_by: 'Ryland Barron',
    issue: 'Tires',
    repaired_by: 'July 16, 2025, 9:45 AM',
    location: 'TEN Care',
  },
  {
    trailer: '1945252B',
    submitted_on: 'July 16, 2025, 11:21 AM',
    submitted_by: 'Kenneth Thompson',
    issue: 'Engine',
    repaired_by: 'July 20, 2025, 18:24 PM',
    location: 'TEN Care',
  },
  {
    trailer: '1945252B',
    submitted_on: 'July 18, 2025, 12:25 PM',
    submitted_by: 'Colson Hurst',
    issue: 'Front Engine',
    repaired_by: 'July 24, 2025, 10:34 PM',
    location: 'TEN Care',
  },
];

export const requestServiceDetailViewData = [
  {
    title: 'Associate Work Orders',
    items: [
      { label: 'Work Order ID', value: '54225365' },
      { label: 'Ten Care Event', value: 'TNX56335522' },
      { label: 'Status', value: 'Service Complete, Begin Invoicing' },
      { label: 'Opened On', value: 'July 12, 2025, 15:45 PM' },
    ],
  },
  {
    title: 'Request Information',
    items: [
      { label: 'Trailer Number', value: '29436H' },
      { label: 'Customer Name and Code', value: '46 Entertainment, INC / 001-100000456-899' },
      { label: 'Service By', value: 'TEN Facility / TNC' },
      { label: 'Service Location', value: '50 Washington Square S, New York, NY 10012, USA' },
      { label: 'Service Repaired By', value: 'July 16, 2025 14:35 PM EDT' },
      { label: 'Loaded?', value: 'No' },
      { label: 'Hazardous Material?', value: 'No' },
      { label: 'Driver Name', value: 'Bryon Jackson / 88452 22455' },
      { label: 'Primary Contact', value: 'Mackenzie Johnson / 88254 33562 Team@4blogistics.com' },
      { label: 'Requested By', value: 'mackenzie@4Blogistics.com' },
      { label: 'Issues', value: 'Body Components' },
      { label: 'Description', value: 'Leaking water into triler' },
      { label: 'Estimate Needed', value: 'No' },
    ],
  },
];

export const userRolesData = [
  {
    id: 1,
    roleName: 'Admin',
    createdOn: '25 June,2025 12:12 pm',
  },
  {
    id: 2,
    roleName: 'Comapany Owner',
    createdOn: '25 Mar,2025 12:12 pm',
  },
  {
    id: 3,
    roleName: 'Project Manager',
    createdOn: '25 Apr,2025 12:12 pm',
  },
  {
    id: 4,
    roleName: 'Super Admin',
    createdOn: '25 Jan,2025 12:12 pm',
  },
];

/*dummy permissions data */
export const dummyPermissions = [
  {
    id: 1,
    modules: 'Home',
    subModules: 'Dashboard-Widgets',
    functionality: '',
    view: { isAvailable: true },
    download: { isAvailable: true },
    create: false,
    update: false,
    delete: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 2,
    modules: 'Fleet Management',
    subModules: 'Fleet View',
    functionality: 'Map',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 3,
    modules: '',
    subModules: 'Fleet View',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 4,
    modules: '',
    subModules: 'Equipment Listing',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 5,
    modules: '',
    subModules: 'Equipment Listing',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 6,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Activity Feed',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 7,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Geofence-List View',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 8,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Geofence-Map View',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 9,
    modules: '',
    subModules: 'Telematics',
    functionality: 'Telematics-Alerts List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 10,
    modules: '',
    subModules: 'DOT &PM Compliance',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 11,
    modules: '',
    subModules: 'DOT & PM Compliance',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 12,
    modules: '',
    subModules: 'Agreements',
    functionality: 'Lease-List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 13,
    modules: '',
    subModules: 'Agreements',
    functionality: 'Lease-Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 14,
    modules: '',
    subModules: 'Agreements',
    functionality: 'Rental-List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 15,
    modules: '',
    subModules: 'Agreements',
    functionality: 'Rental-Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 16,
    modules: 'TEN Care',
    subModules: 'Work Order(M&R)',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 17,
    modules: 'TEN Care',
    subModules: 'Work Order(M&R)',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 18,
    modules: '',
    subModules: 'TEN Care ERS',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 19,
    modules: '',
    subModules: 'TEN Care ERS',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 20,
    modules: '',
    subModules: 'Request Service History',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 21,
    modules: '',
    subModules: 'Request Service History',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 22,
    modules: 'Billing',
    subModules: 'Invoices',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 23,
    modules: '',
    subModules: 'Invoices',
    functionality: 'Pay Now',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 24,
    modules: '',
    subModules: 'Invoices',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 25,
    modules: '',
    subModules: 'Payments',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 26,
    modules: '',
    subModules: 'Payments',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 27,
    modules: 'Reports',
    subModules: 'Report Explorer',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 28,
    modules: '',
    subModules: 'Report Explorer',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 29,
    modules: 'Accounts Management',
    subModules: 'Accounts',
    functionality: 'List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 30,
    modules: '',
    subModules: 'Accounts',
    functionality: 'Details',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 31,
    modules: '',
    subModules: 'Users Management',
    functionality: 'Ten Users-List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
  {
    id: 32,
    modules: '',
    subModules: 'Users Management',
    functionality: 'Customer Users-List',
    create: false,
    update: false,
    view: false,
    delete: false,
    download: false,
    allowAll: false,
    isSelected: true,
  },
];

export const assignedPermissions = [
  {
    permission_name: 'read:dashboard',
    description: 'Read Dashboard Data',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:fleet-map-view',
    description: 'Read Fleet Map view data',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:fleet-list-view',
    description: 'View fleet vehicles in list/table format',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:fleet-list-view-details',
    description: 'View detailed information for individual vehicles in fleet list',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:telematics-activity-feed',
    description: 'View real-time telematics activity and events',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'download:telematics-activity-feed',
    description: 'Download Telematics activity feed',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:telematics-activity-feed-details',
    description: 'View detailed information for specific telematics events',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'write:geofence',
    description: 'Create new geofences and geofencing rules',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'patch:geofence',
    description: 'Edit and modify existing geofences',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'delete:geofence',
    description: 'Remove geofences from the system',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:geofence-map-view',
    description: 'View geofences on map interface',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:geofence-list-view',
    description: 'View geofences in list/table format',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:geofence-list-view-details',
    description: 'View detailed information for individual geofences',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'write:telematics-alerts',
    description: 'Create and configure telematics alerts and notifications',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:telematics-alerts',
    description: 'View existing telematics alerts and their status',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:telematics-alerts-details',
    description: 'View detailed information for specific telematics alerts',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:dot-inspection',
    description: 'View DOT inspection records and compliance data',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'download:dot-inspection',
    description: 'Download dot inspection list',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:dot-inspection-details',
    description: 'View detailed DOT inspection information',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:lease',
    description: 'View vehicle lease agreements and information',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'download:lease',
    description: 'Download lease list',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:lease-details',
    description: 'View detailed lease agreement information',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:rental',
    description: 'View vehicle rental agreements and information',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'download:rental',
    description: 'Download rental list',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:rental-details',
    description: 'View detailed rental agreement information',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:preventive-maintanence',
    description: 'View preventive maintenance schedules and records',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'download:preventive-maintanence',
    description: 'Download Preventive Maintanence',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:preventive-maintanence-details',
    description: 'View detailed preventive maintenance information',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:accounts',
    description: 'View account information and hierarchy',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'download:accounts',
    description: 'Download accounts list',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:account-details',
    description: 'View detailed account information and settings',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:user-management-ten-user-list',
    description: 'View TEN system administrator user list',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'patch:user-management',
    description: 'Edit user information and settings',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'read:user-management',
    description: 'View user lists and basic user information',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'download:user-management',
    description: 'Download Users list',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'patch:user-management-assign-role',
    description: 'Assign roles and permissions to users',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'write:role',
    description: 'Add role',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'patch:role',
    description: 'Edit role',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'delete:role',
    description: 'Delete role',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },

  //currently not using this permissions
  {
    permission_name: 'write:customer',
    description: 'Add customer',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
  {
    permission_name: 'write:user',
    description: 'Add user',
    resource_server_name: 'Ten Customer Portal',
    resource_server_identifier: 'https://ten-customer-portal.com',
  },
];
